# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee7008ec958d170dffa041b1fba245612a5660c6a0706cecf77e3c56a9d7bcbc504ca5d98dc571e87254f80d080f9250bd47c0906ce46398d4334e79e947e80f

test:
  secret_key_base: 7a76092f1dc4dcca78ed4c30afd39785bfb7e36095f0f59905d1fc01c74a92cfa2edf4068279549b36d7e9af9766ed961e1d0188f53131f0eaa4ef1253866269

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
